# Generated by Django 2.2.3 on 2019-08-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190829_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
